# Task Manager Application Deployment and Service
# This file creates the main application deployment and exposes it via a service
# 📝 IMPORTANT: Replace STUDENT_NUMBER with your actual student number (e.g., 0215539)
# another cmment
#Deployment - Manages the Task Manager application Pods
apiVersion: apps/v1 # API version for Deployment resources
kind: Deployment # Resource type - manages application replicas
metadata: # Information about this Deployment
  name: taskmanager-deployment
  namespace: "02220151" # 📝 Replace STUDENT_NUMBER with your number
  labels: # Labels for organizing resources
    app: taskmanager
    component: frontend
    version: v1
    student: "02220151" # 📝 Replace with your student number
spec: # Desired state specification
  replicas: 2 # Run 2 copies for high availability and load distribution
  selector: # How to find Pods managed by this Deployment
    matchLabels: # Pods must have these labels
      app: taskmanager
  template: # Template for creating new Pods
    metadata: # Labels applied to each Pod
      labels:
        app: taskmanager # Must match selector above
        version: v1
    spec: # Pod specification
      containers: # Containers in each Pod
        - name: taskmanager # Container name
          # Docker image from your CI/CD pipeline (update with your DockerHub username)
          image: karmat314/task-manager:591a92f8569b0ad3612a512278f43826516dc0f8
          ports: # Ports exposed by container
            - containerPort: 8000 # Port the Flask app listens on
              name: http # Named port for Service reference
          env: # Environment variables
            - name: DATABASE_URL # Database connection string
              value: "postgresql://myuser:uWhSZwv54wXv1T7F@10.104.0.6:5432/02220151"
            - name: SECRET_KEY # Flask secret key
              value: "kubernetes-secret-key-STUDENT_NUMBER" # 📝 Replace STUDENT_NUMBER
            - name: FLASK_ENV
              value: "production"
